// GENERATED CODE DO NOT EDIT
// This file should be version controlled
import 'package:brick_sqlite/db.dart';
part '20260828160014.migration.dart';
part '20260622053112.migration.dart';
part '20260623151524.migration.dart';
part '20260711234407.migration.dart';
part '20260812200326.migration.dart';

/// All intelligently-generated migrations from all `@Migratable` classes on disk
final migrations = <Migration>{
  const Migration20260828160014(),
  const Migration20260622053112(),
  const Migration20260623151524(),
  const Migration20260711234407(),
  const Migration20260812200326(),
};

/// A consumable database structure including the latest generated migration.
final schema = Schema(
  20260812200326,
  generatorVersion: 1,
  tables: <SchemaTable>{
    SchemaTable(
      'BrickAnimalModel',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('local_id', Column.varchar),
        SchemaColumn('rfid_tag_number', Column.varchar),
        SchemaColumn('visual_tag', Column.varchar),
        SchemaColumn('sex', Column.integer),
        SchemaColumn('breed', Column.varchar),
        SchemaColumn('birth_date', Column.datetime),
        SchemaColumn('category_id', Column.varchar),
        SchemaColumn('category_name', Column.varchar),
        SchemaColumn('lot_id', Column.varchar),
        SchemaColumn('lot_name', Column.varchar),
        SchemaColumn('establishment_id', Column.varchar),
        SchemaColumn('initial_weight', Column.Double),
        SchemaColumn('weighing_method', Column.integer),
        SchemaColumn('weighing_date', Column.datetime),
        SchemaColumn('mother_id', Column.varchar),
        SchemaColumn('father_id', Column.varchar),
        SchemaColumn('coat', Column.varchar),
        SchemaColumn('observations', Column.varchar),
        SchemaColumn('sync_status', Column.integer),
        SchemaColumn('sync_error_code', Column.varchar),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('deleted_at', Column.datetime),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'BrickCategoriaModel',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('local_id', Column.varchar),
        SchemaColumn('establishment_id', Column.varchar),
        SchemaColumn('name', Column.varchar),
        SchemaColumn('description', Column.varchar),
        SchemaColumn('sync_status', Column.integer),
        SchemaColumn('sync_error_code', Column.varchar),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('deleted_at', Column.datetime),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'BrickLotModel',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('local_id', Column.varchar),
        SchemaColumn('establishment_id', Column.varchar),
        SchemaColumn('name', Column.varchar),
        SchemaColumn('boundary_json', Column.varchar),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('deleted_at', Column.datetime),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'BrickOperatingExpenseModel',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('local_id', Column.varchar),
        SchemaColumn('establishment_id', Column.varchar),
        SchemaColumn('amount', Column.varchar),
        SchemaColumn('type', Column.varchar),
        SchemaColumn('category', Column.varchar),
        SchemaColumn('supply', Column.varchar),
        SchemaColumn('date', Column.datetime),
        SchemaColumn('description', Column.varchar),
        SchemaColumn('receipt_number', Column.varchar),
        SchemaColumn('loaded_by_id', Column.varchar),
        SchemaColumn('loaded_by_name', Column.varchar),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('deleted_at', Column.datetime),
        SchemaColumn('custom_category_id', Column.varchar),
        SchemaColumn('sync_status', Column.integer),
        SchemaColumn('sync_error_code', Column.varchar),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'BrickOperatingExpenseCategoryModel',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('local_id', Column.varchar),
        SchemaColumn('establishment_id', Column.varchar),
        SchemaColumn('type', Column.varchar),
        SchemaColumn('name', Column.varchar),
        SchemaColumn('value', Column.varchar),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('deleted_at', Column.datetime),
        SchemaColumn('sync_status', Column.integer),
        SchemaColumn('sync_error_code', Column.varchar),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'BrickPesajeModel',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('local_id', Column.varchar),
        SchemaColumn('establishment_id', Column.varchar),
        SchemaColumn('animal_id', Column.varchar),
        SchemaColumn('weight_kg', Column.Double),
        SchemaColumn('date', Column.datetime),
        SchemaColumn('method', Column.integer),
        SchemaColumn('is_estimated', Column.boolean),
        SchemaColumn('body_condition', Column.Double),
        SchemaColumn('photo_url', Column.varchar),
        SchemaColumn('responsible_id', Column.varchar),
        SchemaColumn('observations', Column.varchar),
        SchemaColumn('sync_status', Column.integer),
        SchemaColumn('sync_error_code', Column.varchar),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('deleted_at', Column.datetime),
      },
      indices: <SchemaIndex>{},
    ),
  },
);
