[project]
name = "ml-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ernesto", email = "epetrich9@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "opencv-python>=5.0.0.93",
    "scikit-learn>=1.9.0",
    "tensorflow>=2.21.0",
]

[project.scripts]
ml-pipeline = "ml_pipeline:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
